sudo: required
language: python
services:
- docker

script:
- docker build -t dockertest .

after_success:
  #log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take built images and push to DOcker hub
  - docker push parag290/docker-react